# Generated by Django 5.0.3 on 2024-04-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
