# Generated by Django 5.0.3 on 2024-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.FileField(upload_to='customers/'),
        ),
    ]
