# Generated by Django 5.0.3 on 2024-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_videoblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial/image')),
                ('logo', models.FileField(blank=True, null=True, upload_to='testimonial/logo')),
                ('description', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
