# Generated by Django 5.0.3 on 2024-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.CharField(max_length=252),
        ),
    ]
