# Generated by Django 5.0.3 on 2024-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_testimonial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketing/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
