# Generated by Django 5.0.3 on 2024-04-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_marketingfeature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/image/')),
                ('title', models.CharField(max_length=148)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='product/logo/')),
            ],
        ),
    ]
