# Generated by Django 5.0.3 on 2024-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], max_length=128)),
            ],
        ),
    ]
