# Generated by Django 5.0.3 on 2024-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_size',
            field=models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '201-500')], default='default', max_length=128),
            preserve_default=False,
        ),
    ]
