# Generated by Django 5.0.3 on 2024-04-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_contact_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='white_logo',
            field=models.FileField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
