# Generated by Django 5.0.3 on 2024-04-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_customer_white_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
    ]
