# Generated by Django 5.0.3 on 2024-04-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
    ]
