# Generated by Django 5.0.3 on 2024-04-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default='a', max_length=148),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(default='b', upload_to='product/image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='c', max_length=148),
            preserve_default=False,
        ),
    ]
