# Generated by Django 5.0.3 on 2024-04-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_product_background_color_product_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.product'),
            preserve_default=False,
        ),
    ]
